import type { Metadata } from "next";
import { ApolloProvider } from "@/providers/ApolloProvider";
import { ChakraProvider } from "@/providers/ChakraProvider";
import { UserProvider } from "@/context/UserContext";
import { AuthGuard } from "@/components/AuthGuard";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <ApolloProvider>
            <UserProvider>
              <Header />
              <AuthGuard>{children}</AuthGuard>
            </UserProvider>
          </ApolloProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
